title: Reading Blog
theme: minima

baseurl: "/skills-github-pages" 
url: "https://WorldlyPirate.github.io"

# 插件必须只包含 GitHub Pages 官方支持的
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag

paginate: 5
paginate_path: "/page:num/"

